name: SFC
channels:
  - conda-forge
dependencies:
  - python == 3.10
  - pip
  # dev
  - black
  - jupyter
  - ipykernel
  - ipywidgets
  # model
  - numpy < 2.0
  # helpers
  - matplotlib
  - networkx
  - tabulate
  # pip
  - pip:
    - black-it